### ISSUE TITLE
thread-test.js

### ISSUE THREAD

**Issue by tangdah** [decafjs/decaf#3]
thread-test.js works; however, the output doesn't look right:

sharedGlobal = 0
sharedGlobal = 2
sharedGlobal = 3
sharedGlobal = 4
sharedGlobal = 5
sharedGlobal = 6
sharedGlobal = 7
sharedGlobal = 8

Whatever happened to shareGlobal = 1?

**Comment by mschwartz** [comment]
Race condition at startup.

**Comment by tangdah** [comment]
So is this the normal behavior for Thread? If I add the line
"console.log('TH2:sharedGlobal = ' + sharedGlobal);"  to the 2nd thread, I
can see that 'sharedGlobal = 1' was created. But somehow it was not printed
to screen by the first thread.

On Sun, Feb 8, 2015 at 10:11 AM, Michael Schwartz <notifications@github.com>
wrote:

> Race condition at startup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/decafjs/decaf/issues/3#issuecomment-73417424>.
>



-- 

Tang Dahong

**Comment by mschwartz** [comment]
Try changing the sleep to 2 in either loop and see what happens.



—
Mike Schwartz

**Comment by tangdah** [comment]
changed sleep of the 2nd thread to 2, here is the output:

$ decaf ~/decaf/examples/thread-test.js
sharedGlobal = 0
sharedGlobal = 1
sharedGlobal = 1
sharedGlobal = 2
sharedGlobal = 2
sharedGlobal = 3
sharedGlobal = 3
sharedGlobal = 4
sharedGlobal = 4
sharedGlobal = 5
sharedGlobal = 5
sharedGlobal = 6
sharedGlobal = 6
^C
exiting


On Sun, Feb 8, 2015 at 10:26 AM, Michael Schwartz <notifications@github.com>
wrote:

> Try changing the sleep to 2 in either loop and see what happens.
>
>
>
> —
> Mike Schwartz
>
>
> On Sun, Feb 8, 2015 at 11:25 AM, tangdah <notifications@github.com> wrote:
>
> > So is this the normal behavior for Thread? If I add the line
> > "console.log('TH2:sharedGlobal = ' + sharedGlobal);" to the 2nd thread, I
> > can see that 'sharedGlobal = 1' was created. But somehow it was not
> printed
> > to screen by the first thread.
> > On Sun, Feb 8, 2015 at 10:11 AM, Michael Schwartz <
> notifications@github.com>
> > wrote:
> >> Race condition at startup.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/decafjs/decaf/issues/3#issuecomment-73417424>.
> >>
> > --
> > Tang Dahong
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/decafjs/decaf/issues/3#issuecomment-73418004
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/decafjs/decaf/issues/3#issuecomment-73418063>.
>



-- 

Tang Dahong

**Comment by mschwartz** [comment]
There is a race between the two threads.  If it is timed right, one will barely get to increment the global twice before the other can print it.




Changing sleep time should help you understand what is going on between the threads.



—
Mike Schwartz

**Comment by tangdah** [comment]
OK, I see. The 2 threads run parallel but not necessarily at the same speed
(and the first thread was slowed down initially because it had to call
console.log). Thanks.

On Sun, Feb 8, 2015 at 10:32 AM, Michael Schwartz <notifications@github.com>
wrote:

> There is a race between the two threads.  If it is timed right, one will
> barely get to increment the global twice before the other can print it.
>
>
>
>
> Changing sleep time should help you understand what is going on between
> the threads.
>
>
>
> —
> Mike Schwartz
>
>
> On Sun, Feb 8, 2015 at 11:30 AM, tangdah <notifications@github.com> wrote:
>
> > changed sleep of the 2nd thread to 2, here is the output:
> > $ decaf ~/decaf/examples/thread-test.js
> > sharedGlobal = 0
> > sharedGlobal = 1
> > sharedGlobal = 1
> > sharedGlobal = 2
> > sharedGlobal = 2
> > sharedGlobal = 3
> > sharedGlobal = 3
> > sharedGlobal = 4
> > sharedGlobal = 4
> > sharedGlobal = 5
> > sharedGlobal = 5
> > sharedGlobal = 6
> > sharedGlobal = 6
> > ^C
> > exiting
> > On Sun, Feb 8, 2015 at 10:26 AM, Michael Schwartz <
> notifications@github.com>
> > wrote:
> >> Try changing the sleep to 2 in either loop and see what happens.
> >>
> >>
> >>
> >> —
> >> Mike Schwartz
> >>
> >>
> >> On Sun, Feb 8, 2015 at 11:25 AM, tangdah <notifications@github.com>
> wrote:
> >>
> >> > So is this the normal behavior for Thread? If I add the line
> >> > "console.log('TH2:sharedGlobal = ' + sharedGlobal);" to the 2nd
> thread, I
> >> > can see that 'sharedGlobal = 1' was created. But somehow it was not
> >> printed
> >> > to screen by the first thread.
> >> > On Sun, Feb 8, 2015 at 10:11 AM, Michael Schwartz <
> >> notifications@github.com>
> >> > wrote:
> >> >> Race condition at startup.
> >> >>
> >> >> —
> >> >> Reply to this email directly or view it on GitHub
> >> >> <https://github.com/decafjs/decaf/issues/3#issuecomment-73417424>.
> >> >>
> >> > --
> >> > Tang Dahong
> >> > ---
> >> > Reply to this email directly or view it on GitHub:
> >> > https://github.com/decafjs/decaf/issues/3#issuecomment-73418004
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/decafjs/decaf/issues/3#issuecomment-73418063>.
> >>
> > --
> > Tang Dahong
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/decafjs/decaf/issues/3#issuecomment-73418207
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/decafjs/decaf/issues/3#issuecomment-73418308>.
>



-- 

Tang Dahong

**Comment by mschwartz** [comment]
Exactly.




See sync() function built into rhino to provide synchronized functions as in Java programs, too.



—
Mike Schwartz

**Comment by mschwartz** [comment]
One more note.  The intent of the example is to show:




1. Threads are easy!

2. Parallel threads can share global variables.






—
Mike Schwartz
