### ISSUE TITLE
setFollowRedirects(true)

### ISSUE THREAD

**Issue by tangdah** [decafjs/decaf#5]
setFollowRedirects(true) does not work if the protocol is changed from http to https during the redirect. Is this supposed to be handled automatically by the http module or not?

**Comment by mschwartz** [comment]
HttpClient uses HttpURLConnection.  There is a separate HttpsURLConnection
that is not used at this time.  It wouldn't be hard to add, but see the
stackoverflow link I provide below.

http://docs.oracle.com/javase/7/docs/api/java/net/HttpURLConnection.html



http://stackoverflow.com/questions/1884230/java-doesnt-follow-redirect-in-urlconnection

**Comment by tangdah** [comment]
Ok thanks.
