### ISSUE TITLE
Has this project been publicized anywhere?

### ISSUE THREAD

**Issue by Asuza** [decafjs/decaf#8]
I just came across this after checking in on the SilkJS project, and I'm excited. I want to find something to use decaf for. Everything that I use Node for, I use in a synchronous way anyway.

For what seems like a fantastic project, it seems like nobody knows about it (based on how many people have starred it). Are you guys waiting to get it a bit further along before sharing it? I'd love to see it gain a following.

**Comment by mschwartz** [comment]
We haven't chosen to promote decafjs yet.  We want to have an orderly launch which means we need the WWW site up, documentation fully complete (you can use the source, if worse comes to worse), unit tests fully implemented, and proper versioning.

We are using decafjs for our internal projects and it is working great.

Feel free to use it and ask any questions, report any bugs, etc.

Any work you do with it that is public, let us know so we can see decafjs in action.
